---
- name: Installing required Python pgsql module for Ansible to manage databases
  apt:
    pkg: python-psycopg2
    state: installed

- name: creating SQL mail user
  postgresql_user:
    name: mail
    state: present
  become: true
  become_user: postgres

- name: creating mailserver SQL database
  postgresql_db:
    name: mailserver
    encoding: UTF-8
    lc_collate: C
    lc_ctype: C
    template: template0
    owner: mail
  become: true
  become_user: postgres

- name: creating SQL pgadmin user
  postgresql_user:
    name: pgadmin
    password: "{{ispmail_pgadmin_password}}"
    state: present
    db: mailserver
    priv: ALL
  become: true
  become_user: postgres

- name: creating MySQL user for roundcube
  postgresql_user:
    name: roundcubeuser
    password: "{{ispmail_mysql_roundcube_password}}"
    state: present
  become: true
  become_user: postgres

- name: creating Roundcube SQL database
  postgresql_db:
    name: roundcube
    encoding: UTF-8
    lc_collate: C
    lc_ctype: C
    template: template0
    owner: roundcubeuser
  become: true
  become_user: postgres

- name: Creating the postgres user map
  blockinfile:
    dest: /etc/postgresql/9.4/main/pg_ident.conf
    marker: "### {mark} ANSIBLE MANAGED BLOCK : MAILMAP ###"
    insertafter: "^#\\s-+"
    content: |
      mailmap         dovecot                 mail
      mailmap         postfix                 mail
      mailmap         root                    mail

- name: Allowing unix socket connections on mailserver database
  lineinfile:
    dest: /etc/postgresql/9.4/main/pg_hba.conf
    regexp: "^local\\s+mail\\s+all\\s+peer\\s+map=mailmap$"
    insertbefore: "^#\\sIPv4\\slocal.+"
    line: "local   mail            all             peer                    map=mailmap"

- name: Allowing pgadmin connections on mailserver database
  lineinfile:
    dest: /etc/postgresql/9.4/main/pg_hba.conf
    regexp: "^host\\s+mailserver\\s+pgadmin\\s+127.0.0.1/32\\s+md5$"
    insertbefore: "^#\\sIPv4\\slocal.+"
    line: "host    mailserver      pgadmin         127.0.0.1/32            md5"

- name: Allowing IP connections on roundcube database
  lineinfile:
    dest: /etc/postgresql/9.4/main/pg_hba.conf
    regexp: "^host\\s+roundcube\\s+roundcubeuser\\s+127.0.0.1/32\\s+md5$"
    insertafter: "^#\\sIPv4\\slocal.+"
    line: "host    roundcube       roundcubeuser   127.0.0.1/32            md5"

- name: copying SQL database schema to server
  copy: src=schema.sql dest=/tmp

#- name: setting up SQL schema of mailserver database
#  postgresql_db: name=mailserver state=import target=/tmp/schema.sql
#  become: true
#  become_user: postgres

# Ugly, not idempotent fix, to change

- name: setting up SQL schema of mailserver database
  shell: "psql mailserver < /tmp/schema.sql"
  become: true
  become_user: postgres

- name: copying SQL test data to server
  copy: src=test.sql dest=/tmp
  when: ispmail_populate_test_data == true
  become: true
  become_user: postgres

- name: populating the database with test data
  postgresql_db: name=mailserver state=import target=/tmp/test.sql
  when: ispmail_populate_test_data == true
  become: true
  become_user: postgres
