---
ispmail_dovecot_auth_mechanisms: plain login
ispmail_dovecot_database_password: ''
ispmail_dovecot_databases:
  - name: local
    address: /var/run/postgresql

ispmail_dovecot_doveadm_password: ChangeMe

dovecot_internal_key: /etc/ssl/dovecot/privkey.pem
dovecot_internal_cert: /etc/ssl/dovecot/cert.pem
dovecot_internal_csr: /etc/ssl/dovecot/node.csr
